2024-05-25 21:54:58,528:ERROR:Error in processing data
Traceback (most recent call last):
  File "D:\UWien\NTF\main\NTF_testbuild_v1.0.py", line 114, in process_data_thread
    aggregated_df = pd.concat(aggregated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanu\AppData\Roaming\Python\Python312\site-packages\pandas\core\reshape\concat.py", line 382, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "C:\Users\chanu\AppData\Roaming\Python\Python312\site-packages\pandas\core\reshape\concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanu\AppData\Roaming\Python\Python312\site-packages\pandas\core\reshape\concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
2024-05-25 22:00:23,133:ERROR:Error in processing data
Traceback (most recent call last):
  File "D:\UWien\NTF\main\NTF_testbuild_v1.0.py", line 115, in process_data_thread
    data = calculate_parameters(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\UWien\NTF\main\NTF_testbuild_v1.0.py", line 18, in calculate_parameters
    data['dx'] = data['X'].diff().fillna(0)
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\chanu\AppData\Roaming\Python\Python312\site-packages\pandas\core\series.py", line 3120, in diff
    result = algorithms.diff(self._values, periods)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chanu\AppData\Roaming\Python\Python312\site-packages\pandas\core\algorithms.py", line 1435, in diff
    out_arr[res_indexer] = op(arr[res_indexer], arr[lag_indexer])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'str' and 'str'
